apps = [
  {name = "neovim", config_path = ".config/nvim", file_names = ["coc-settings.json", "init.vim"]},
  {name = "neovim", config_path = ".config/nvim", file_names = ["coc-settings.json", "init.vim"]},
  {name = "neovim", config_path = ".config/nvim", file_names = ["coc-settings.json", "init.vim"]},
  {name = "neovim", config_path = ".config/nvim", file_names = ["coc-settings.json", "init.vim"]},
]

