[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.mksettings]
script = "mkdir -p $HOME/.config/setman/settings"

[tasks.copy-binary]
script = "sudo install -s -Dm755 ./target/release/setman /usr/bin/setman"

[tasks.install]
dependencies = [
  "clean",
  "build",
  "mksettings",
  "copy-binary"
]

[tasks.update]
dependencies = [
  "clean",
  "build",
  "copy-binary"
]
